AppBundle\Entity\Article:
    type: entity
    table: article
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 100
        content:
            type: text